# This is a basic workflow to help you get started with Actions

name: Build Docker Container on a schedule

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0 * * 1"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          
      - name: Get date for tag
        id: tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d')"
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/sdlc-ops/wait-for-it:${{steps.tag.outputs.tag}}
        
